// <auto-generated />
namespace LanguageLearnerWeb.Migrations.AppContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddProfileMaterials : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProfileMaterials));
        
        string IMigrationMetadata.Id
        {
            get { return "201611261113066_AddProfileMaterials"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
